name: Create ZIP on Release

on:
  release:
    types: [created]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP archive
      run: zip -r xslt_release.zip *.xml *.xslt

    - name: Upload ZIP to release
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./xslt_release.zip
        asset_name: xslt_release.zip
        asset_content_type: application/zip
