name: Create ZIP on Release

on:
  release:
    types: [created]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up release tag as variable
      run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

    - name: Create ZIP archive
      run: zip -r xslt_release_${{ github.event.release.tag_name }}.zip *.xml *.xslt

    - name: Upload ZIP to release
      uses: softprops/action-gh-release@v1
      with:
        files: xslt_release_${{ github.event.release.tag_name }}.zip
